all: sample2D

sample2D: Sample_GL3_2D.cpp glad.c
	g++ -o sample2D Sample_GL3_2D.cpp glad.c -framework OpenGL -lglfw -lftgl -lSOIL -I/usr/local/include/freetype2 -I/usr/local/include -L/usr/local/lib

clean:
	rm sample2D
